export enum ServerEvents {

    // Disconnection events
    DISCONNECTION_RESPONSE_SUCCESS = "DISCONNECTION_RESPONSE_SUCCESS",
    DISCONNECTION_RESPONSE_FAIL = "DISCONNECTION_RESPONSE_FAIL",

    // Lobby creation events
    CREATE_LOBBY_RESPONSE_SUCCESS = "CREATE_LOBBY_RESPONSE_SUCCESS",
    CREATE_LOBBY_RESPONSE_FAIL = "CREATE_LOBBY_RESPONSE_FAIL",

}