export enum Events {
    CONNECTION = "connection",
    DISCONNECT = "disconnect",

    // Lobby creation management
    CREATE_LOBBY_REQUEST = "CREATE_LOBBY_REQUEST",
    CREATE_LOBBY_RESPONSE_SUCCESS = "CREATE_LOBBY_RESPONSE_SUCCESS",
    CREATE_LOBBY_RESPONSE_FAIL = "CREATE_LOBBY_RESPONSE_FAIL",

}